# Generated by Django 5.1.7 on 2025-03-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('procesador', models.CharField(max_length=100)),
                ('memoria', models.CharField(max_length=100)),
                ('almacenamiento', models.CharField(max_length=100)),
                ('tarjeta_grafica', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.URLField()),
            ],
        ),
    ]
